/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.AdoptInfoBLL;
import BLL.AdoptiveParentBLL;
import BLL.ChildBLL;
import Entity.AdoptInfo;
import Entity.AdoptiveParent;
import Entity.Child;
import Utilities.ControlFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fAdoptInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form fAdoptInfo
     */
    private int flag=0;
    AdoptInfoBLL adoptInfoBLL =new AdoptInfoBLL();
    ControlFormat control =new ControlFormat();
    ChildBLL childBLL =new ChildBLL();
    AdoptiveParentBLL adoptiveParentBLL=new AdoptiveParentBLL();
    ChildBLL childBLL1=new ChildBLL();
    public fAdoptInfo() {
        initComponents();
        btnSaveAdoptInfo.setEnabled(false);
        control.bindingAdoptInfo(jTableAdoptInfo, adoptInfoBLL.LoadAdoptInfo());
        cbNameAPaAdoptInfo.removeAllItems();
        cbNameChildAdoptInfo.removeAllItems();
        for(Child child: childBLL.LoadChild())
        {
            cbNameChildAdoptInfo.addItem(child.getName());
        }
        for(AdoptiveParent adoptiveParent: adoptiveParentBLL.LoadAdoptiveParent())
        {
            cbNameAPaAdoptInfo.addItem(adoptiveParent.getName());
        }
        jDChAdoptDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txfSearchAdoptInfo = new javax.swing.JTextField();
        btnSearchAdoptInfo = new javax.swing.JButton();
        cbSearchAdoptInfo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbNameAPaAdoptInfo = new javax.swing.JComboBox<>();
        cbNameChildAdoptInfo = new javax.swing.JComboBox<>();
        jDChAdoptDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdoptInfo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAddAdoptInfo = new javax.swing.JButton();
        btnEditAdoptInfo = new javax.swing.JButton();
        btnDelAdoptInfo = new javax.swing.JButton();
        btnSaveAdoptInfo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("QUẢN LÝ VIỆC NHẬN NUÔI TRẺ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(348, 37, 475, 37);

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Tìm theo tên của:");

        txfSearchAdoptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchAdoptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchAdoptInfo.setForeground(new java.awt.Color(51, 0, 153));
        btnSearchAdoptInfo.setText("TÌM KIẾM");
        btnSearchAdoptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAdoptInfoActionPerformed(evt);
            }
        });

        cbSearchAdoptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbSearchAdoptInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trẻ", "Người nhận nuôi", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfSearchAdoptInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(cbSearchAdoptInfo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSearchAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbSearchAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchAdoptInfo)
                    .addComponent(txfSearchAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(21, 130, 540, 120);

        jPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Tên người nhận nuôi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Tên trẻ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Ngày nhận");

        cbNameAPaAdoptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbNameAPaAdoptInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNameChildAdoptInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbNameChildAdoptInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDChAdoptDate.setDateFormatString("dd-MM-yyyy");
        jDChAdoptDate.setFocusable(false);
        jDChAdoptDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbNameChildAdoptInfo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDChAdoptDate, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(cbNameAPaAdoptInfo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbNameAPaAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNameChildAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDChAdoptDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 250, 539, 160);

        jTableAdoptInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAdoptInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdoptInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAdoptInfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(578, 134, 690, 558);

        jPanel4.setOpaque(false);

        btnAddAdoptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddAdoptInfo.setForeground(new java.awt.Color(51, 0, 153));
        btnAddAdoptInfo.setText("THÊM");
        btnAddAdoptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdoptInfoActionPerformed(evt);
            }
        });

        btnEditAdoptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditAdoptInfo.setForeground(new java.awt.Color(51, 0, 153));
        btnEditAdoptInfo.setText("CẬP NHẬT");
        btnEditAdoptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAdoptInfoActionPerformed(evt);
            }
        });

        btnDelAdoptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelAdoptInfo.setForeground(new java.awt.Color(51, 0, 153));
        btnDelAdoptInfo.setText("XÓA");
        btnDelAdoptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAdoptInfoActionPerformed(evt);
            }
        });

        btnSaveAdoptInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveAdoptInfo.setForeground(new java.awt.Color(51, 0, 153));
        btnSaveAdoptInfo.setText("LƯU");
        btnSaveAdoptInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAdoptInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEditAdoptInfo)
                .addGap(26, 26, 26)
                .addComponent(btnDelAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSaveAdoptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdoptInfo)
                    .addComponent(btnEditAdoptInfo)
                    .addComponent(btnDelAdoptInfo)
                    .addComponent(btnSaveAdoptInfo))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(90, 430, 480, 47);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia6.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1400, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ClearText()
    {
       cbNameAPaAdoptInfo.setSelectedItem(null);
       cbNameChildAdoptInfo.setSelectedItem(null);
       jDChAdoptDate.setDate(new Date());
    }
    public boolean  Insert()
    {
        String nameadopt =cbNameAPaAdoptInfo.getSelectedItem().toString();
        int idadopt =adoptiveParentBLL.getID(nameadopt);
        String namechild =cbNameChildAdoptInfo.getSelectedItem().toString();
        int idchild=childBLL.getID(namechild);
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date adoptdate =jDChAdoptDate.getDate();
        String str_adoptdate =formatter.format(adoptdate);
        if(nameadopt.equals("")|| namechild.equals("") ||adoptdate.equals(null))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin đầy đủ");
            return false;
        }
        else
        {
            if(adoptInfoBLL.InsertAdoptInfo(idadopt, idchild, str_adoptdate))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công chi tiết nhận trẻ");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại chi tiết nhận trẻ");
                return false;
            }
        }
    }
    public boolean  Update()
    {
        String nameadopt =cbNameAPaAdoptInfo.getSelectedItem().toString();
        int idadopt =adoptiveParentBLL.getID(nameadopt);
        String namechild =cbNameChildAdoptInfo.getSelectedItem().toString();
        int idchild=childBLL.getID(namechild);
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date adoptdate =jDChAdoptDate.getDate();
        String str_adoptdate =formatter.format(adoptdate);
        if(nameadopt.equals("")|| namechild.equals("") ||adoptdate.equals(null))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin đầy đủ");
            return false;
        }
        else
        {
            if(adoptInfoBLL.UpdateAdoptInfo(idadopt, idchild, str_adoptdate))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công chi tiết nhận trẻ");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại chi tiết nhận trẻ");
                return false;
            }
        }
    }
    public boolean Delete()
    {
        String nameadopt =cbNameAPaAdoptInfo.getSelectedItem().toString();
        int idadopt =adoptiveParentBLL.getID(nameadopt);
        String namechild =cbNameChildAdoptInfo.getSelectedItem().toString();
        int idchild=childBLL.getID(namechild);
        if(adoptInfoBLL.DeleteAdoptInfo(idadopt, idchild))
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công chi tiết nhận trẻ");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Xóa thất bại chi tiết nhận trẻ");
                return false;
            }
    }
    private void btnAddAdoptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdoptInfoActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnAddAdoptInfo.setEnabled(false);
        btnEditAdoptInfo.setEnabled(false);
        btnDelAdoptInfo.setEnabled(false);
        btnSaveAdoptInfo.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddAdoptInfoActionPerformed

    private void btnEditAdoptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAdoptInfoActionPerformed
        // TODO add your handling code here:
        btnAddAdoptInfo.setEnabled(false);
        btnEditAdoptInfo.setEnabled(false);
        btnDelAdoptInfo.setEnabled(false);
        btnSaveAdoptInfo.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditAdoptInfoActionPerformed

    private void btnDelAdoptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAdoptInfoActionPerformed
        // TODO add your handling code here:
        btnAddAdoptInfo.setEnabled(false);
        btnEditAdoptInfo.setEnabled(false);
        btnDelAdoptInfo.setEnabled(false);
        btnSaveAdoptInfo.setEnabled(true);
        flag=3;
    }//GEN-LAST:event_btnDelAdoptInfoActionPerformed

    private void btnSaveAdoptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAdoptInfoActionPerformed
        // TODO add your handling code here:
        if(flag==1)
        {
            if(Insert())
            {
                control.bindingAdoptInfo(jTableAdoptInfo, adoptInfoBLL.LoadAdoptInfo());
                ClearText();
                btnSaveAdoptInfo.setEnabled(false);
            }
            btnEditAdoptInfo.setEnabled(true);
            btnAddAdoptInfo.setEnabled(true);
            btnDelAdoptInfo.setEnabled(true);
        }
        if(flag==2)
        {
            if(Update())
            {
                control.bindingAdoptInfo(jTableAdoptInfo, adoptInfoBLL.LoadAdoptInfo());
                ClearText();
                btnSaveAdoptInfo.setEnabled(false);
            }
            btnEditAdoptInfo.setEnabled(true);
            btnAddAdoptInfo.setEnabled(true);
            btnDelAdoptInfo.setEnabled(true);
        }
        if(flag==3)
        {
            if(Delete())
            {
                control.bindingAdoptInfo(jTableAdoptInfo, adoptInfoBLL.LoadAdoptInfo());
                ClearText();
                btnSaveAdoptInfo.setEnabled(false);
            }
            btnEditAdoptInfo.setEnabled(true);
            btnAddAdoptInfo.setEnabled(true);
            btnDelAdoptInfo.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveAdoptInfoActionPerformed

    private void btnSearchAdoptInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAdoptInfoActionPerformed
        // TODO add your handling code here:
        String key =txfSearchAdoptInfo.getText().toString();
        if(cbSearchAdoptInfo.getSelectedItem().toString().equals("Trẻ"))
        {
            control.bindingAdoptInfo(jTableAdoptInfo, adoptInfoBLL.SearchAdoptInfo_Child(key));
        }
        if(cbSearchAdoptInfo.getSelectedItem().equals("Người nhận nuôi"))
        {
            control.bindingAdoptInfo(jTableAdoptInfo, adoptInfoBLL.SearchAdoptInfo_Adopt(key));
        }
        txfSearchAdoptInfo.setText("");
        cbSearchAdoptInfo.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchAdoptInfoActionPerformed

    private void jTableAdoptInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdoptInfoMouseClicked
        // TODO add your handling code here:
        int row =jTableAdoptInfo.getSelectedRow();
        String nameadopt =jTableAdoptInfo.getValueAt(row, 0).toString();
        String namechild=jTableAdoptInfo.getValueAt(row, 1).toString();
        if(jTableAdoptInfo.getValueAt(row, 0).toString().equals(nameadopt))
            cbNameAPaAdoptInfo.setSelectedItem(nameadopt);
        if(jTableAdoptInfo.getValueAt(row, 1).toString().equals(namechild))
            cbNameChildAdoptInfo.setSelectedItem(namechild);
        jDChAdoptDate.setDate((Date)jTableAdoptInfo.getModel().getValueAt(row, 2));
    }//GEN-LAST:event_jTableAdoptInfoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdoptInfo;
    private javax.swing.JButton btnDelAdoptInfo;
    private javax.swing.JButton btnEditAdoptInfo;
    private javax.swing.JButton btnSaveAdoptInfo;
    private javax.swing.JButton btnSearchAdoptInfo;
    private javax.swing.JComboBox<String> cbNameAPaAdoptInfo;
    private javax.swing.JComboBox<String> cbNameChildAdoptInfo;
    private javax.swing.JComboBox<String> cbSearchAdoptInfo;
    private com.toedter.calendar.JDateChooser jDChAdoptDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdoptInfo;
    private javax.swing.JTextField txfSearchAdoptInfo;
    // End of variables declaration//GEN-END:variables
}
