/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ExpenseBLL;
import Utilities.ControlFormat;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fExpense extends javax.swing.JInternalFrame {

    /**
     * Creates new form fExpense
     */
    ControlFormat control = new ControlFormat();
    ExpenseBLL expenseBLL = new ExpenseBLL();
    int flag = 0;
    Toolkit tk =Toolkit.getDefaultToolkit();
    public fExpense() {
        initComponents();
        control.bindingExpense(jTableExpense, expenseBLL.LoadExpense());
        jDChExpenseDate.setDate(new Date());
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();  
        jLabel9.setSize(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSearchExpense = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbMonthSearchExpense = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfYearSearchExpense = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txfIDExpense = new javax.swing.JTextField();
        txfNameExpense = new javax.swing.JTextField();
        jDChExpenseDate = new com.toedter.calendar.JDateChooser();
        txfTotalExpense = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExpense = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAddExpense = new javax.swing.JButton();
        btnEditExpense = new javax.swing.JButton();
        btnDelExpense = new javax.swing.JButton();
        btnSaveExpense = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("QUẢN LÝ CHI TIÊU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 50, 284, 37);

        jPanel1.setOpaque(false);

        btnSearchExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchExpense.setText("TÌM KIẾM");
        btnSearchExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchExpenseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tìm thông tin chi tiêu theo thời gian");

        cbMonthSearchExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbMonthSearchExpense.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tháng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Năm");

        txfYearSearchExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfYearSearchExpense)
                            .addComponent(cbMonthSearchExpense, 0, 111, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addComponent(btnSearchExpense)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMonthSearchExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txfYearSearchExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearchExpense)
                        .addGap(34, 34, 34))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(41, 113, 409, 154);

        jPanel2.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mã chi tiêu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tên chi tiêu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ngày chi");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tổng tiền");

        txfIDExpense.setEditable(false);
        txfIDExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfNameExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDChExpenseDate.setDateFormatString("dd-MM-yyyy");
        jDChExpenseDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfTotalExpense.setEditable(false);
        txfTotalExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfIDExpense)
                    .addComponent(txfNameExpense)
                    .addComponent(jDChExpenseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(txfTotalExpense))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txfIDExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(txfNameExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jDChExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txfTotalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(41, 295, 448, 181);

        jTableExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExpenseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExpense);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(531, 113, 730, 528);

        jPanel4.setOpaque(false);

        btnAddExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddExpense.setText("THÊM");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        btnEditExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditExpense.setText("CẬP NHẬT");
        btnEditExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditExpenseActionPerformed(evt);
            }
        });

        btnDelExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelExpense.setText("XÓA");
        btnDelExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelExpenseActionPerformed(evt);
            }
        });

        btnSaveExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveExpense.setText("LƯU");
        btnSaveExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEditExpense)
                .addGap(30, 30, 30)
                .addComponent(btnDelExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSaveExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddExpense)
                    .addComponent(btnEditExpense)
                    .addComponent(btnDelExpense)
                    .addComponent(btnSaveExpense))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(22, 494, 503, 47);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1340, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Xóa dữ liệu 
    public void ClearText()
    {
        txfIDExpense.setText("");
        txfNameExpense.setText("");
        txfTotalExpense.setText("");
    }
    
    //Thêm chi tiêu
    public boolean InsertExpense()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        String NameExpense = txfNameExpense.getText();
        String ExpenseDate = formatter.format(jDChExpenseDate.getDate());
        
        if(NameExpense.equals("") || ExpenseDate.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            return false;
        }
        else
        {
            if(expenseBLL.InsertExpense(NameExpense, ExpenseDate))
            {
                JOptionPane.showMessageDialog(this, "Thêm chi tiêu thành công");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm chi tiêu thất bại");
                return false;
            }
        }
    }
    
    public boolean UpdateExpense()
    {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        int IDExpense = Integer.parseInt(txfIDExpense.getText());
        String NameExpense = txfNameExpense.getText();
        String ExpenseDate = formatter.format(jDChExpenseDate.getDate());
        
        if(NameExpense.equals("") || ExpenseDate.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            return false;
        }
        else
        {
            if(expenseBLL.UpdateExpense(IDExpense, NameExpense, ExpenseDate))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật chi tiêu thành công");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật chi tiêu thất bại");
                return false;
            }
        }
    }
    public void DeleteExpense()
    {
        int IDExpense = Integer.parseInt(txfIDExpense.getText());
        if(expenseBLL.DeleteExpense(IDExpense))
            JOptionPane.showMessageDialog(this, "Xóa chi tiêu thành công");
        else
            JOptionPane.showMessageDialog(this, "Xóa chi tiêu thất bại");
    }
    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnAddExpense.setEnabled(false);
        btnEditExpense.setEnabled(false);
        btnDelExpense.setEnabled(false);
        btnSaveExpense.setEnabled(true);
        flag = 1;
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    private void btnEditExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditExpenseActionPerformed
        // TODO add your handling code here:
        btnAddExpense.setEnabled(false);
        btnEditExpense.setEnabled(false);
        btnDelExpense.setEnabled(false);
        btnSaveExpense.setEnabled(true);
        flag = 2;
    }//GEN-LAST:event_btnEditExpenseActionPerformed

    private void btnDelExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelExpenseActionPerformed
        // TODO add your handling code here:
        btnAddExpense.setEnabled(false);
        btnEditExpense.setEnabled(false);
        btnDelExpense.setEnabled(false);
        btnSaveExpense.setEnabled(true);
        flag = 3;
    }//GEN-LAST:event_btnDelExpenseActionPerformed

    private void btnSaveExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveExpenseActionPerformed
        // TODO add your handling code here:
        if(flag == 1)
        {
            if(InsertExpense())
            {
                btnAddExpense.setEnabled(true);
                btnEditExpense.setEnabled(true);
                btnDelExpense.setEnabled(true);
                btnSaveExpense.setEnabled(false);
                control.bindingExpense(jTableExpense, expenseBLL.LoadExpense());
                ClearText();
            }
        }
        if(flag == 2)
        {
            if(UpdateExpense())
            {
                btnAddExpense.setEnabled(true);
                btnEditExpense.setEnabled(true);
                btnDelExpense.setEnabled(true);
                btnSaveExpense.setEnabled(false);
                control.bindingExpense(jTableExpense, expenseBLL.LoadExpense());
                ClearText();
            }
        }
        if(flag == 3)
        {
            btnAddExpense.setEnabled(true);
            btnEditExpense.setEnabled(true);
            btnDelExpense.setEnabled(true);
            btnSaveExpense.setEnabled(false);
            control.bindingExpense(jTableExpense, expenseBLL.LoadExpense());
            ClearText();
        }
    }//GEN-LAST:event_btnSaveExpenseActionPerformed

    private void btnSearchExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchExpenseActionPerformed
        // TODO add your handling code here:
        int Month, Year;
        if(cbMonthSearchExpense.getSelectedItem() == null)
            Month = 0;
        else Month = Integer.parseInt(cbMonthSearchExpense.getSelectedItem().toString()) ;
        
        if(txfYearSearchExpense.getText().equals(""))
            Year = 0;
        else Year = Integer.parseInt(txfYearSearchExpense.getText());
        
        control.bindingExpense(jTableExpense, expenseBLL.SearchExpense(Month, Year));
        txfYearSearchExpense.setText("");
    }//GEN-LAST:event_btnSearchExpenseActionPerformed

    private void jTableExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExpenseMouseClicked
        // TODO add your handling code here:
        int row = jTableExpense.getSelectedRow();
        txfIDExpense.setText(jTableExpense.getValueAt(row, 0).toString());
        txfNameExpense.setText(jTableExpense.getValueAt(row, 1).toString());
        jDChExpenseDate.setDate((Date) jTableExpense.getValueAt(row, 2));
        txfTotalExpense.setText(jTableExpense.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTableExpenseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnDelExpense;
    private javax.swing.JButton btnEditExpense;
    private javax.swing.JButton btnSaveExpense;
    private javax.swing.JButton btnSearchExpense;
    private javax.swing.JComboBox<String> cbMonthSearchExpense;
    private com.toedter.calendar.JDateChooser jDChExpenseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExpense;
    private javax.swing.JTextField txfIDExpense;
    private javax.swing.JTextField txfNameExpense;
    private javax.swing.JTextField txfTotalExpense;
    private javax.swing.JTextField txfYearSearchExpense;
    // End of variables declaration//GEN-END:variables
}
