/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import BLL.ExpenseBLL;
import BLL.ExpenseInfoBLL;
import Entity.Expense;
import Utilities.ControlFormat;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fExpenseInfo extends javax.swing.JInternalFrame {

    /** Creates new form fExpenseInfo */
    ControlFormat control = new ControlFormat();
    ExpenseBLL expenseBLL = new ExpenseBLL();
    ExpenseInfoBLL expenseInfoBLL = new ExpenseInfoBLL();
    int flag = 0;
    
    public fExpenseInfo() {
        initComponents();
        cbIDExpenseExpenseInfo.removeAllItems();
        Toolkit tk =Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int)tk.getScreenSize().getHeight();  
        for(Expense expense : expenseBLL.LoadExpense())
        {
            cbIDExpenseExpenseInfo.addItem(String.valueOf(expense.getIDExpense()));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSearchExpense = new javax.swing.JButton();
        jDChSearchExpenseInfo = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbIDExpenseExpenseInfo = new javax.swing.JComboBox<>();
        txfIDExpenseInfo = new javax.swing.JTextField();
        txfNameExpenseInfo = new javax.swing.JTextField();
        txfMoneyExpenseInfo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnAddExpenseInfo = new javax.swing.JButton();
        btnEditExpenseInfo = new javax.swing.JButton();
        btnDelExpenseInfo = new javax.swing.JButton();
        btnSaveExpenseInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExpenseInfo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ CHI TIẾT CHI TIÊU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(355, 11, 429, 37);

        jPanel1.setOpaque(false);

        btnSearchExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchExpense.setText("TÌM KIẾM");
        btnSearchExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchExpenseActionPerformed(evt);
            }
        });

        jDChSearchExpenseInfo.setDateFormatString("dd-MM-yyyy");
        jDChSearchExpenseInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jDChSearchExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchExpense)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDChSearchExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchExpense))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(22, 121, 475, 47);

        jPanel2.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã chi tiết chi tiêu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên chi tiết chi tiêu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số tiền");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã chi tiêu");

        cbIDExpenseExpenseInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbIDExpenseExpenseInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbIDExpenseExpenseInfo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbIDExpenseExpenseInfoItemStateChanged(evt);
            }
        });

        txfIDExpenseInfo.setEditable(false);
        txfIDExpenseInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfNameExpenseInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfMoneyExpenseInfo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfNameExpenseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addComponent(txfMoneyExpenseInfo)
                        .addComponent(txfIDExpenseInfo))
                    .addComponent(cbIDExpenseExpenseInfo, 0, 314, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbIDExpenseExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(txfIDExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfNameExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfMoneyExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(22, 208, 490, 182);

        jPanel4.setOpaque(false);

        btnAddExpenseInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddExpenseInfo.setText("THÊM");
        btnAddExpenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseInfoActionPerformed(evt);
            }
        });

        btnEditExpenseInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditExpenseInfo.setText("CẬP NHẬT");
        btnEditExpenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditExpenseInfoActionPerformed(evt);
            }
        });

        btnDelExpenseInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelExpenseInfo.setText("XÓA");
        btnDelExpenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelExpenseInfoActionPerformed(evt);
            }
        });

        btnSaveExpenseInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveExpenseInfo.setText("LƯU");
        btnSaveExpenseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveExpenseInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEditExpenseInfo)
                .addGap(33, 33, 33)
                .addComponent(btnDelExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnSaveExpenseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddExpenseInfo)
                    .addComponent(btnEditExpenseInfo)
                    .addComponent(btnDelExpenseInfo)
                    .addComponent(btnSaveExpenseInfo))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(33, 423, 500, 47);

        jTableExpenseInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableExpenseInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExpenseInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExpenseInfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(593, 111, 527, 460);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 1370, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Thêm CTCT
    public boolean InsertExpenseInfo()
    {
        int IDExpense;
        if(cbIDExpenseExpenseInfo.getSelectedItem() == null)
            IDExpense = 0;
        else IDExpense = Integer.parseInt(cbIDExpenseExpenseInfo.getSelectedItem().toString());
        String NameExpenseInfo = txfNameExpenseInfo.getText();
        float Money;
        if(txfMoneyExpenseInfo.getText().equals(""))
            Money = 0;
        else Money = Float.parseFloat(txfMoneyExpenseInfo.getText());
        
        if(NameExpenseInfo.equals("") || txfMoneyExpenseInfo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            return false;
        }
        else
        {
            if(expenseInfoBLL.InsertExpenseInfo(IDExpense, NameExpenseInfo, Money))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công chi tiết chi tiêu");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại chi tiết chi tiêu");
                return false;
            }
        }
    }
    //Cập nhật CTCT
    public boolean UpdateExpenseInfo()
    {
        int IDExpense;
        if(cbIDExpenseExpenseInfo.getSelectedItem() == null)
            IDExpense = 0;
        else IDExpense = Integer.parseInt(cbIDExpenseExpenseInfo.getSelectedItem().toString());
        
        int IDExpenseInfo;
        if(txfIDExpenseInfo.getText().equals(""))
            IDExpenseInfo = 0;
        else IDExpenseInfo = Integer.parseInt(txfIDExpenseInfo.getText());
        
        String NameExpenseInfo = txfNameExpenseInfo.getText();
        
        float Money;
        if(txfMoneyExpenseInfo.getText().equals(""))
            Money = 0;
        else Money = Float.parseFloat(txfMoneyExpenseInfo.getText());
        
        if(NameExpenseInfo.equals("") || txfMoneyExpenseInfo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            return false;
        }
        else
        {
            if(expenseInfoBLL.UpdateExpenseInfo(IDExpense, IDExpenseInfo, NameExpenseInfo, Money))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công chi tiết chi tiêu");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại chi tiết chi tiêu");
                return false;
            }
        }
    }
    //Xóa CTCT
    public void DeleteExpenseInfo()
    {
        int IDExpense;
        if(cbIDExpenseExpenseInfo.getSelectedItem() == null)
            IDExpense = 0;
        else IDExpense = Integer.parseInt(cbIDExpenseExpenseInfo.getSelectedItem().toString());
        
        int IDExpenseInfo;
        if(txfIDExpenseInfo.getText().equals(""))
            IDExpenseInfo = 0;
        else IDExpenseInfo = Integer.parseInt(txfIDExpenseInfo.getText());
        
        if(expenseInfoBLL.DeleteExpenseInfo(IDExpense, IDExpenseInfo))
            JOptionPane.showMessageDialog(this, "Xóa thành công chi tiết chi tiêu");
        else
            JOptionPane.showMessageDialog(this, "Xóa thất bại chi tiết chi tiêu");
    }
    // Xóa dữ liệu
    public void ClearText()
    {
        txfIDExpenseInfo.setText("");
        txfMoneyExpenseInfo.setText("");
        txfNameExpenseInfo.setText("");
    }
    private void btnAddExpenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseInfoActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnAddExpenseInfo.setEnabled(false);
        btnEditExpenseInfo.setEnabled(false);
        btnDelExpenseInfo.setEnabled(false);
        btnSaveExpenseInfo.setEnabled(true);
        flag = 1;
    }//GEN-LAST:event_btnAddExpenseInfoActionPerformed

    private void btnEditExpenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditExpenseInfoActionPerformed
        // TODO add your handling code here:
        btnAddExpenseInfo.setEnabled(false);
        btnEditExpenseInfo.setEnabled(false);
        btnDelExpenseInfo.setEnabled(false);
        btnSaveExpenseInfo.setEnabled(true);
        flag = 2;
    }//GEN-LAST:event_btnEditExpenseInfoActionPerformed

    private void btnDelExpenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelExpenseInfoActionPerformed
        // TODO add your handling code here:
        btnAddExpenseInfo.setEnabled(false);
        btnEditExpenseInfo.setEnabled(false);
        btnDelExpenseInfo.setEnabled(false);
        btnSaveExpenseInfo.setEnabled(true);
        flag = 3;
    }//GEN-LAST:event_btnDelExpenseInfoActionPerformed

    private void btnSaveExpenseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveExpenseInfoActionPerformed
        // TODO add your handling code here:
        int IDExpense = Integer.parseInt(cbIDExpenseExpenseInfo.getSelectedItem().toString());
        if(flag == 1)
        {
            if(InsertExpenseInfo())
            {
                btnAddExpenseInfo.setEnabled(true);
                btnEditExpenseInfo.setEnabled(true);
                btnDelExpenseInfo.setEnabled(true);
                btnSaveExpenseInfo.setEnabled(false);
                control.bindingExpenseInfo(jTableExpenseInfo, expenseInfoBLL.LoadExpenseInfo(IDExpense));
                ClearText();
            }
        }
        if(flag == 2)
        {
            if(UpdateExpenseInfo())
            {
                btnAddExpenseInfo.setEnabled(true);
                btnEditExpenseInfo.setEnabled(true);
                btnDelExpenseInfo.setEnabled(true);
                btnSaveExpenseInfo.setEnabled(false);
                control.bindingExpenseInfo(jTableExpenseInfo, expenseInfoBLL.LoadExpenseInfo(IDExpense));
                ClearText();
            }
        }
        if(flag == 3)
        {
            DeleteExpenseInfo();
            btnAddExpenseInfo.setEnabled(true);
            btnEditExpenseInfo.setEnabled(true);
            btnDelExpenseInfo.setEnabled(true);
            btnSaveExpenseInfo.setEnabled(false);
            control.bindingExpenseInfo(jTableExpenseInfo, expenseInfoBLL.LoadExpenseInfo(IDExpense));
            ClearText();
        }
    }//GEN-LAST:event_btnSaveExpenseInfoActionPerformed

    private void btnSearchExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchExpenseActionPerformed
        // TODO add your handling code here:
        control.bindingExpenseInfo(jTableExpenseInfo, expenseInfoBLL.SearchExpenseInfo(jDChSearchExpenseInfo.getDate().toString()));
        jDChSearchExpenseInfo.setDate(new Date());
    }//GEN-LAST:event_btnSearchExpenseActionPerformed

    private void jTableExpenseInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExpenseInfoMouseClicked
        // TODO add your handling code here:
        int row = jTableExpenseInfo.getSelectedRow();
        cbIDExpenseExpenseInfo.setSelectedItem(jTableExpenseInfo.getValueAt(row, 0).toString());
        txfIDExpenseInfo.setText(jTableExpenseInfo.getValueAt(row, 1).toString());
        txfNameExpenseInfo.setText(jTableExpenseInfo.getValueAt(row, 2).toString());
        txfMoneyExpenseInfo.setText(jTableExpenseInfo.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTableExpenseInfoMouseClicked

    private void cbIDExpenseExpenseInfoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbIDExpenseExpenseInfoItemStateChanged
        // TODO add your handling code here:
        int IDExpense;
        if(cbIDExpenseExpenseInfo.getSelectedItem() == null)
            IDExpense = 0;
        else IDExpense = Integer.parseInt(cbIDExpenseExpenseInfo.getSelectedItem().toString());
        control.bindingExpenseInfo(jTableExpenseInfo, expenseInfoBLL.LoadExpenseInfo(IDExpense));
    }//GEN-LAST:event_cbIDExpenseExpenseInfoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpenseInfo;
    private javax.swing.JButton btnDelExpenseInfo;
    private javax.swing.JButton btnEditExpenseInfo;
    private javax.swing.JButton btnSaveExpenseInfo;
    private javax.swing.JButton btnSearchExpense;
    private javax.swing.JComboBox<String> cbIDExpenseExpenseInfo;
    private com.toedter.calendar.JDateChooser jDChSearchExpenseInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExpenseInfo;
    private javax.swing.JTextField txfIDExpenseInfo;
    private javax.swing.JTextField txfMoneyExpenseInfo;
    private javax.swing.JTextField txfNameExpenseInfo;
    // End of variables declaration//GEN-END:variables

}
