/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ExpenseBLL;
import BLL.SponsorshipBLL;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author STIREN
 */
public class fReportFinance extends javax.swing.JInternalFrame {

    /**
     * Creates new form fReportFinance
     */
    ExpenseBLL expenseBLL = new ExpenseBLL();
    SponsorshipBLL sponsorshipBLL = new SponsorshipBLL();
    
    public fReportFinance() {
        initComponents();
        jDChFromDateRPFinance.setDate(new Date());
        jDChToDateRPFinance.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDChFromDateRPFinance = new com.toedter.calendar.JDateChooser();
        jDChToDateRPFinance = new com.toedter.calendar.JDateChooser();
        btnRPFinance = new javax.swing.JButton();
        btnPrintRPFinance = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRPFinance = new javax.swing.JTextArea();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("BÁO CÁO TÌNH HÌNH TÀI CHÍNH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Thời gian thống kê");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Từ ngày");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Đến ngày");

        jDChFromDateRPFinance.setDateFormatString("dd-MM-yyyy");
        jDChFromDateRPFinance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jDChToDateRPFinance.setDateFormatString("dd-MM-yyyy");
        jDChToDateRPFinance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDChFromDateRPFinance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDChToDateRPFinance, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jDChFromDateRPFinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDChToDateRPFinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnRPFinance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRPFinance.setText("THỐNG KÊ");
        btnRPFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPFinanceActionPerformed(evt);
            }
        });

        btnPrintRPFinance.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPrintRPFinance.setText("IN BÁO CÁO");
        btnPrintRPFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintRPFinanceActionPerformed(evt);
            }
        });

        txaRPFinance.setEditable(false);
        txaRPFinance.setColumns(20);
        txaRPFinance.setRows(5);
        jScrollPane1.setViewportView(txaRPFinance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnRPFinance)
                        .addGap(113, 113, 113)
                        .addComponent(btnPrintRPFinance))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrintRPFinance)
                            .addComponent(btnRPFinance))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    private void btnRPFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPFinanceActionPerformed
        // TODO add your handling code here:
        String FromDate, ToDate;
        if(jDChFromDateRPFinance.getDate() == null)
            FromDate = "";
        else
            FromDate = formatter.format(jDChFromDateRPFinance.getDate());
        if(jDChToDateRPFinance.getDate() == null)
            ToDate = "";
        else
        ToDate = formatter.format(jDChToDateRPFinance.getDate());
        
        Date Today = new Date();
        
        txaRPFinance.setText("");
        txaRPFinance.append("\t\t CÔ NHI VIỆN HƯỚNG DƯƠNG\n\n");
        txaRPFinance.append("Địa chỉ: 184 Phan Văn Khỏe, Phường 5, Quận 1, TP Hồ Chí Minh\n");
        txaRPFinance.append("Số điện thoại: (08) 3821 0199\n\n");
        txaRPFinance.append("\t\t BÁO CÁO TÀI CHÍNH\n");
        txaRPFinance.append("\t\t (Từ ngày " + FromDate + " đến ngày " + ToDate + ")\n\n");
        txaRPFinance.append("Ngày lập báo cáo: " + formatter.format(Today) + "\n\n");
        txaRPFinance.append("Tổng số tiền tài trợ: " + sponsorshipBLL.getTotalSponsorship(FromDate, ToDate) + "\n");
        txaRPFinance.append("Tổng số tiền chi tiêu: " + expenseBLL.getTotalExpense(FromDate, ToDate) + "\n");
        txaRPFinance.append("Tổng tiền quỹ hiện tại: " + expenseBLL.getFund());
    }//GEN-LAST:event_btnRPFinanceActionPerformed

    private void btnPrintRPFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintRPFinanceActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            txaRPFinance.print();
        } catch (PrinterException ex) {
            Logger.getLogger(fReportFinance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintRPFinanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintRPFinance;
    private javax.swing.JButton btnRPFinance;
    private com.toedter.calendar.JDateChooser jDChFromDateRPFinance;
    private com.toedter.calendar.JDateChooser jDChToDateRPFinance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaRPFinance;
    // End of variables declaration//GEN-END:variables
}
