/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.StaffCategogyBLL;
import Utilities.ControlFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fStaffCategogy extends javax.swing.JInternalFrame {

    /**
     * Creates new form fStaffCategogy
     */
    StaffCategogyBLL staffCategogyBLL =new StaffCategogyBLL();
    ControlFormat control =new ControlFormat();
    private int flag=0;
    public fStaffCategogy() {
        initComponents();
        control.bindingStaffCategogy(jTableStaffCategogy, staffCategogyBLL.LoadStaffCategogy());
    }
    //Hàm chuẩn hóa tên
    public String chuanHoa(String str) {
        str = str.trim();
        str = str.replaceAll("\\s+", " ");
        return str;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfIDStaffCategogy = new javax.swing.JTextField();
        txfNameStaffCategogy = new javax.swing.JTextField();
        txfSearchStaffCategogy = new javax.swing.JTextField();
        btnSearchStaffCategogy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAddStaffCategogy = new javax.swing.JButton();
        btnEditStaffCategogy = new javax.swing.JButton();
        btnDelStaffCategogy = new javax.swing.JButton();
        btnSaveStaffCategogy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStaffCategogy = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("QUẢN LÝ LOẠI NHÂN VIÊN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(536, 22, 404, 37);

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã loại nhân viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên loại nhân viên");

        txfIDStaffCategogy.setEditable(false);
        txfIDStaffCategogy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfNameStaffCategogy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txfSearchStaffCategogy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchStaffCategogy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchStaffCategogy.setText("TÌM KIẾM");
        btnSearchStaffCategogy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffCategogyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfIDStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txfNameStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txfSearchStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSearchStaffCategogy)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearchStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStaffCategogy))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfIDStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txfNameStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 433, 193);

        jPanel4.setOpaque(false);

        btnAddStaffCategogy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddStaffCategogy.setText("THÊM");
        btnAddStaffCategogy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffCategogyActionPerformed(evt);
            }
        });

        btnEditStaffCategogy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditStaffCategogy.setText("CẬP NHẬT");
        btnEditStaffCategogy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffCategogyActionPerformed(evt);
            }
        });

        btnDelStaffCategogy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelStaffCategogy.setText("XÓA");
        btnDelStaffCategogy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStaffCategogyActionPerformed(evt);
            }
        });

        btnSaveStaffCategogy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaveStaffCategogy.setText("LƯU");
        btnSaveStaffCategogy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStaffCategogyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEditStaffCategogy)
                .addGap(26, 26, 26)
                .addComponent(btnDelStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStaffCategogy)
                    .addComponent(btnEditStaffCategogy)
                    .addComponent(btnDelStaffCategogy)
                    .addComponent(btnSaveStaffCategogy))
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 301, 469, 47);

        jTableStaffCategogy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableStaffCategogy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStaffCategogy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStaffCategogyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStaffCategogy);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(485, 90, 740, 550);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bia2.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1520, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableStaffCategogyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStaffCategogyMouseClicked
        // TODO add your handling code here:
        int row=jTableStaffCategogy.getSelectedRow();
        txfIDStaffCategogy.setText(jTableStaffCategogy.getValueAt(row, 0).toString());
        txfNameStaffCategogy.setText(jTableStaffCategogy.getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTableStaffCategogyMouseClicked

    private void btnAddStaffCategogyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffCategogyActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnAddStaffCategogy.setEnabled(false);
        btnEditStaffCategogy.setEnabled(false);
        btnDelStaffCategogy.setEnabled(false);
        btnSaveStaffCategogy.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddStaffCategogyActionPerformed

    private void btnEditStaffCategogyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffCategogyActionPerformed
        // TODO add your handling code here:
        btnAddStaffCategogy.setEnabled(false);
        btnEditStaffCategogy.setEnabled(false);
        btnDelStaffCategogy.setEnabled(false);
        btnSaveStaffCategogy.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditStaffCategogyActionPerformed

    private void btnDelStaffCategogyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStaffCategogyActionPerformed
        // TODO add your handling code here:
        btnAddStaffCategogy.setEnabled(false);
        btnEditStaffCategogy.setEnabled(false);
        btnDelStaffCategogy.setEnabled(false);
        btnSaveStaffCategogy.setEnabled(true);
        flag=3;
    }//GEN-LAST:event_btnDelStaffCategogyActionPerformed

    private void btnSaveStaffCategogyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStaffCategogyActionPerformed
        // TODO add your handling code here:
        if(flag==1)
        {
            if(Insert())
            {
                btnSaveStaffCategogy.setEnabled(false);
                control.bindingStaffCategogy(jTableStaffCategogy, staffCategogyBLL.LoadStaffCategogy());
                ClearText();
            }
            btnAddStaffCategogy.setEnabled(true);
            btnEditStaffCategogy.setEnabled(true);
            btnDelStaffCategogy.setEnabled(true);
        }
        if(flag==2)
        {
            if(Update())
            {
                btnSaveStaffCategogy.setEnabled(false);
                control.bindingStaffCategogy(jTableStaffCategogy, staffCategogyBLL.LoadStaffCategogy());
                ClearText();
            }
            btnAddStaffCategogy.setEnabled(true);
            btnEditStaffCategogy.setEnabled(true);
            btnDelStaffCategogy.setEnabled(true);
        }
        if(flag==3)
        {
            if(Delete()==true)
            {
                btnSaveStaffCategogy.setEnabled(false);
                control.bindingStaffCategogy(jTableStaffCategogy, staffCategogyBLL.LoadStaffCategogy());
                ClearText();
            }
            btnAddStaffCategogy.setEnabled(true);
            btnEditStaffCategogy.setEnabled(true);
            btnDelStaffCategogy.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveStaffCategogyActionPerformed

    private void btnSearchStaffCategogyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffCategogyActionPerformed
        // TODO add your handling code here:
        control.bindingStaffCategogy(jTableStaffCategogy, staffCategogyBLL.SearchStaffCategogy(txfSearchStaffCategogy.getText().toString()));
        txfSearchStaffCategogy.setText("");
    }//GEN-LAST:event_btnSearchStaffCategogyActionPerformed
    //Thêm loại nhân viên
    public boolean  Insert()
    {
        String name =txfNameStaffCategogy.getText().toString();
        name=chuanHoa(name);
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên loại nhân viên");
            return false;
        }
        else{
            if(staffCategogyBLL.InsertStaffCategogy(name))
            {
                JOptionPane.showMessageDialog(this,"Thêm loại nhân viên thành công");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm loại nhân viên thất bại");
                return false;
            }
        }
    }
    //Cập nhật loại nhân viên
    public boolean  Update()
    {
        int id=Integer.parseInt(txfIDStaffCategogy.getText());
        String name =txfNameStaffCategogy.getText().toString();
        name=chuanHoa(name);
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên loại nhân viên");
            return false;
        }
        else{
            if(staffCategogyBLL.UpdateStaffCategogy(id, name))
            {
                JOptionPane.showMessageDialog(this,"Cập nhật loại nhân viên thành công");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật loại nhân viên thất bại");
                return false;
            }
        }
    }
    //Xóa loại nhân viên
    public boolean  Delete()
    {
        int id=Integer.parseInt(txfIDStaffCategogy.getText());
        if(staffCategogyBLL.DeleteStaffCategogy(id))
       {
           JOptionPane.showMessageDialog(this,"Xóa loại nhân viên thành công");
           return true;
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Xóa loại nhân viên thất bại");
           return false;
       }

   }
   
    //Xóa text
    public void ClearText()
    {
        txfIDStaffCategogy.setText("");
        txfNameStaffCategogy.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaffCategogy;
    private javax.swing.JButton btnDelStaffCategogy;
    private javax.swing.JButton btnEditStaffCategogy;
    private javax.swing.JButton btnSaveStaffCategogy;
    private javax.swing.JButton btnSearchStaffCategogy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStaffCategogy;
    private javax.swing.JTextField txfIDStaffCategogy;
    private javax.swing.JTextField txfNameStaffCategogy;
    private javax.swing.JTextField txfSearchStaffCategogy;
    // End of variables declaration//GEN-END:variables
}
