/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.StaffCategogyBLL;
import BLL.StaffBLL;
import Entity.StaffCategogy;
import Utilities.ControlFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class fStaff extends javax.swing.JInternalFrame {

    /**
     * Creates new form fStaff
     */
    StaffCategogyBLL staffCategogyBLL =new StaffCategogyBLL();
    StaffBLL staffBLL=new StaffBLL();
    ControlFormat control =new ControlFormat();
    private int flag=0;
    public fStaff() {
        initComponents();
        cbStaffCategogy.removeAllItems();
        control.bindingStaff(jTableStaff, staffBLL.LoadStaff());
        for(StaffCategogy   staffCategogy: staffCategogyBLL.LoadStaffCategogy())
        {
            cbStaffCategogy.addItem(staffCategogy.getName());
        }
        jDChStartStaff.setDate(new Date());
    }
    //Hàm chuẩn hóa tên
    public String chuanHoa(String str) {
        str = str.trim();
        str = str.replaceAll("\\s+", " ");
        return str;
    }
 
    public String chuanHoaDanhTuRieng(String str) {
        str = chuanHoa(str.toLowerCase());
        String temp[] = str.split(" ");
        str = ""; // ? ^-^
        for (int i = 0; i < temp.length; i++) {
            str += String.valueOf(temp[i].charAt(0)).toUpperCase() + temp[i].substring(1);
            if (i < temp.length - 1) // ? ^-^
                str += " ";
        }
        return str;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txfIDStaff = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfNameStaff = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDChBirthdayStaff = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txfAddressStaff = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfPhoneStaff = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDChStartStaff = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cbStaffCategogy = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnAddStaff = new javax.swing.JButton();
        btnEditStaff = new javax.swing.JButton();
        btnDelStaff = new javax.swing.JButton();
        btnSaveStaff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStaff = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txfSearchStaff = new javax.swing.JTextField();
        btnSearchStaff = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        txfIDStaff.setEditable(false);
        txfIDStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Tên nhân viên");

        txfNameStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Ngày sinh");

        jDChBirthdayStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Địa chỉ");

        txfAddressStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Điện thoại");

        txfPhoneStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txfPhoneStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfPhoneStaffKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Ngày vào làm");

        jDChStartStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Loại nhân viên");

        cbStaffCategogy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbStaffCategogy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Ngày sinh");

        buttonGroup1.add(rbtnMale);
        rbtnMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnMale.setText("Nam");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnFemale);
        rbtnFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnFemale.setText("Nữ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Trạng thái");

        cbStatus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Đã nghỉ việc" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(txfPhoneStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbStaffCategogy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfIDStaff)
                            .addComponent(txfNameStaff)
                            .addComponent(txfAddressStaff)
                            .addComponent(jDChStartStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jDChBirthdayStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtnFemale))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbStaffCategogy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfIDStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(rbtnMale)
                    .addComponent(rbtnFemale))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDChBirthdayStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfPhoneStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDChStartStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnAddStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnAddStaff.setText("THÊM");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnEditStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEditStaff.setText("CẬP NHẬT");
        btnEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffActionPerformed(evt);
            }
        });

        btnDelStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDelStaff.setText("XÓA");
        btnDelStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStaffActionPerformed(evt);
            }
        });

        btnSaveStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSaveStaff.setText("LƯU");
        btnSaveStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEditStaff)
                .addGap(26, 26, 26)
                .addComponent(btnDelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSaveStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStaff)
                    .addComponent(btnEditStaff)
                    .addComponent(btnDelStaff)
                    .addComponent(btnSaveStaff))
                .addContainerGap())
        );

        jTableStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "Địa chỉ", "Điện thoại", "Ngày vào làm ", "Title 8"
            }
        ));
        jTableStaff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStaff);

        txfSearchStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnSearchStaff.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSearchStaff.setText("TÌM KIẾM");
        btnSearchStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSearchStaff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStaff))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffActionPerformed
        // TODO add your handling code here:
        String key =txfSearchStaff.getText().toString();
        control.bindingStaff(jTableStaff, staffBLL.SearchStaff(key));
        txfSearchStaff.setText("");
    }//GEN-LAST:event_btnSearchStaffActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
        ClearText();
        btnAddStaff.setEnabled(false);
        btnEditStaff.setEnabled(false);
        btnDelStaff.setEnabled(false);
        btnSaveStaff.setEnabled(true);
        flag=1;
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffActionPerformed
        // TODO add your handling code here:
        btnAddStaff.setEnabled(false);
        btnEditStaff.setEnabled(false);
        btnDelStaff.setEnabled(false);
        btnSaveStaff.setEnabled(true);
        flag=2;
    }//GEN-LAST:event_btnEditStaffActionPerformed

    private void btnDelStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStaffActionPerformed
        // TODO add your handling code here:
        btnAddStaff.setEnabled(false);
        btnEditStaff.setEnabled(false);
        btnDelStaff.setEnabled(false);
        btnSaveStaff.setEnabled(true);
        flag=3;
    }//GEN-LAST:event_btnDelStaffActionPerformed

    private void btnSaveStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStaffActionPerformed
        // TODO add your handling code here:
        if(flag==1)
        {
            if(Insert())
            {
                btnSaveStaff.setEnabled(false);
                control.bindingStaff(jTableStaff, staffBLL.LoadStaff());
                ClearText();
            }
            btnAddStaff.setEnabled(true);
            btnEditStaff.setEnabled(true);
            btnDelStaff.setEnabled(true);
        }
        if(flag==2)
        {
            if(Update())
            {
                btnSaveStaff.setEnabled(false);
                control.bindingStaff(jTableStaff, staffBLL.LoadStaff());
                ClearText();
            }
            btnAddStaff.setEnabled(true);
            btnEditStaff.setEnabled(true);
            btnDelStaff.setEnabled(true);
        }
        if(flag==3)
        {
            if(Delete())
            {
                btnSaveStaff.setEnabled(false);
                control.bindingStaff(jTableStaff, staffBLL.LoadStaff());
                ClearText();
            }
            btnAddStaff.setEnabled(true);
            btnEditStaff.setEnabled(true);
            btnDelStaff.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveStaffActionPerformed

    private void jTableStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStaffMouseClicked
        // TODO add your handling code here:
        int row =jTableStaff.getSelectedRow();
        txfIDStaff.setText(jTableStaff.getValueAt(row, 0).toString());
        txfNameStaff.setText(jTableStaff.getValueAt(row, 1).toString());
        if(jTableStaff.getValueAt(row, 2).toString().equals("Nam"))
            rbtnMale.setSelected(true);
        if(jTableStaff.getValueAt(row, 2).toString().equals("Nữ"))
            rbtnFemale.setSelected(true);
        jDChBirthdayStaff.setDate((Date)jTableStaff.getModel().getValueAt(row, 3));
        txfAddressStaff.setText(jTableStaff.getValueAt(row, 4).toString());
        txfPhoneStaff.setText(jTableStaff.getValueAt(row, 5).toString());
        jDChStartStaff.setDate((Date)jTableStaff.getModel().getValueAt(row, 6));
        String categogy =jTableStaff.getValueAt(row, 7).toString();
        cbStaffCategogy.setSelectedItem(categogy);
    }//GEN-LAST:event_jTableStaffMouseClicked
     public void ClearText()
    {
        cbStaffCategogy.setSelectedIndex(0);
        cbStatus.setSelectedItem(0);
        txfIDStaff.setText("");
        txfNameStaff.setText("");
        txfAddressStaff.setText("");
        txfPhoneStaff.setText("");
        jDChBirthdayStaff.setDate(null);
        jDChStartStaff.setDate(new Date());
        rbtnMale.setSelected(true);
    }
    public boolean  Insert()
    {
        String name =txfNameStaff.getText().toString();
        name=chuanHoaDanhTuRieng(name);
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date birthday =jDChBirthdayStaff.getDate();
        String strbirthday =formatter.format(birthday);
        String address =txfAddressStaff.getText().toString();
        address=chuanHoa(address);
        String phonenumber =txfPhoneStaff.getText().toString();
        Date startwork =jDChStartStaff.getDate();
        String strstartwork =formatter.format(startwork);
        String namecategogy =cbStaffCategogy.getSelectedItem().toString();
        String  status=cbStatus.getSelectedItem().toString();
        int status_ = 1;
        if(status.equals("Đang làm việc"))
            status_=1;
        if(status.equals("Đã nghỉ việc"))
            status_=0;
        int idcategogy =staffCategogyBLL.getID(namecategogy);
        String sex="" ;
        if(rbtnMale.isSelected())
            sex="Nam";
        if(rbtnFemale.isSelected())
            sex="Nữ";
        if(name.equals("")|| strbirthday.equals("")|| strstartwork.equals("")||address.equals("")||phonenumber.equals("")||namecategogy.equals("") || sex.equals("")||status.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            return false;
        }
        else
        {
            if(staffBLL.InsertStaff(name, sex, strbirthday, address, phonenumber, strstartwork, idcategogy,status_))
            {
                JOptionPane.showMessageDialog(this, "Thêm thành công nhân viên");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thêm thất bại nhân viên");
                return false;
            }
        }
    }
    public boolean  Update()
    {
        int id= Integer.parseInt(txfIDStaff.getText());
        String name =txfNameStaff.getText().toString();
        name=chuanHoaDanhTuRieng(name);
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date birthday =jDChBirthdayStaff.getDate();
        String strbirthday =formatter.format(birthday);
        String address =txfAddressStaff.getText().toString();
        address=chuanHoa(address);
        String phonenumber =txfPhoneStaff.getText().toString();
        Date startwork =jDChStartStaff.getDate();
        String strstartwork =formatter.format(startwork);
        String namecategogy =cbStaffCategogy.getSelectedItem().toString();
        int idcategogy =staffCategogyBLL.getID(namecategogy);
         String  status=cbStatus.getSelectedItem().toString();
        int status_ = 1;
        if(status.equals("Đang làm việc"))
            status_=1;
        if(status.equals("Đã nghỉ việc"))
            status_=0;
        String sex="" ;
        if(rbtnMale.isSelected())
            sex="Nam";
        if(rbtnFemale.isSelected())
            sex="Nữ";
        if(name.equals("")|| strbirthday.equals("")|| strstartwork.equals("")||address.equals("")||phonenumber.equals("")||namecategogy.equals("") || sex.equals("")|| status.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            return false;
        }
        else
        {
            if(staffBLL.UpdateStaff(id, name, sex, strbirthday, address, phonenumber, strstartwork, idcategogy,status_))
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công nhân viên");
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại nhân viên");
                return false;
            }
        }
    }
    public boolean Delete()
    {
        int id =Integer.parseInt(txfIDStaff.getText());
        if(staffBLL.DeleteStaff(id))
        {
            JOptionPane.showMessageDialog(this, "Xóa thành công nhân viên");
            return true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Xóa thất bại nhân viên");
            return false;
        }
       
    }

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void txfPhoneStaffKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfPhoneStaffKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) || txfPhoneStaff.getText().length() >= 10)
            evt.consume();
    }//GEN-LAST:event_txfPhoneStaffKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnDelStaff;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JButton btnSaveStaff;
    private javax.swing.JButton btnSearchStaff;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbStaffCategogy;
    private javax.swing.JComboBox<String> cbStatus;
    private com.toedter.calendar.JDateChooser jDChBirthdayStaff;
    private com.toedter.calendar.JDateChooser jDChStartStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStaff;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextField txfAddressStaff;
    private javax.swing.JTextField txfIDStaff;
    private javax.swing.JTextField txfNameStaff;
    private javax.swing.JTextField txfPhoneStaff;
    private javax.swing.JTextField txfSearchStaff;
    // End of variables declaration//GEN-END:variables
}
